services:
  - type: web
    name: poultry-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: main.settings
