services:
  - type: web
    name: online-ecommerce-butcher-shop
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://lakshmi_broliers_user:mtAOZJHjUKQHD64Ya5aAxrYDq4fmOmpA@dpg-d8ncbi3tqb8s73d182s0-a/polutary_db"
      - key: PYTHON_VERSION
        value: "3.14.3"
    autoDeploy: true
