# Generated by Django 5.2.8 on 2026-06-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'upi'), ('card', 'card'), ('netbanking', 'netbanking'), ('cod', 'cash on delivery')], max_length=20),
        ),
    ]
