# Generated by Django 5.2.8 on 2026-06-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_instructions_order_product_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
    ]
