# Generated by Django 6.0.6 on 2026-10-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_saved_customer_details(apps, schema_editor):
    user_app, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app, user_model)
    Order = apps.get_model("orders", "Order")
    CustomerProfile = apps.get_model("home", "CustomerProfile")
    CustomerAddress = apps.get_model("home", "CustomerAddress")

    for user in User.objects.filter(is_superuser=False).iterator():
        latest_order = (
            Order.objects.filter(user_id=user.pk)
            .exclude(location__isnull=True)
            .exclude(location="")
            .order_by("-order_id")
            .first()
        )
        if latest_order is None:
            continue

        mobile = "".join(character for character in (latest_order.mobile or "") if character.isdigit())
        if len(mobile) == 12 and mobile.startswith("91"):
            mobile = mobile[2:]
        if len(mobile) != 10:
            continue

        if not user.first_name and latest_order.name:
            user.first_name = latest_order.name[:150]
            user.save(update_fields=["first_name"])
        CustomerProfile.objects.get_or_create(user_id=user.pk, defaults={"mobile": mobile})
        CustomerAddress.objects.get_or_create(
            user_id=user.pk,
            is_default=True,
            defaults={
                "label": "Home",
                "recipient_name": (latest_order.name or user.username)[:100],
                "mobile": mobile,
                "address": latest_order.location[:500],
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0012_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=10)),
                ('recipient_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', 'created_at', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user')],
            },
        ),
        migrations.RunPython(backfill_saved_customer_details, migrations.RunPython.noop),
    ]
